[package]
authors = ['ctt']
edition = '2018'
name = 'ctt-pallet-kp'
version = "2.0.0-alpha.3"
license = "Unlicense"
homepage = "https://substrate.dev"
repository = "https://github.com/pfcoder/substrate/"
description = "Knowledge power pallet "

[dependencies]
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false, features = ["derive"] }
safe-mix = { default-features = false, version = '1.0.0' }

[dependencies.frame-support]
default-features = false
version = "2.0.0-alpha.2"
path = "../../../../frame/support"

[dependencies.system]
default-features = false
package = 'frame-system'
version = "2.0.0-alpha.2"
path = "../../../../frame/system"
[dev-dependencies.sp-core]
default-features = false
version = "2.0.0-alpha.2"
path = "../../../../primitives/core"

[dev-dependencies.sp-io]
default-features = false
version = "2.0.0-alpha.2"
path = "../../../../primitives/io"

[dependencies.sp-runtime]
default-features = false
version = "2.0.0-alpha.2"
path = "../../../../primitives/runtime"

[features]
default = ['std']
std = [
	'codec/std',
	'frame-support/std',
	'safe-mix/std',
	'system/std',
	'sp-runtime/std'
]
