# Github action to ensure the `release` tag always tracks latest release

name: Retag release

on:
  release:
    types: [ published, prereleased ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Git tag
        uses: s3krit/walking-tag-action@master
        # Avoid running this step twice when it's a prerelease (once for the prereleased action and once for the published action)
        if: ( github.event.release.prerelease == true && github.event.action == 'prereleased' ) || github.event.release.prerelease == false
        with:
          TAG_NAME: release
          TAG_MESSAGE: Latest release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
