# Github action to ensure the `release` tag always tracks latest release

name: Automate new issues

on:
  release:
    types: [ published, prereleased ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Git tag
        uses: s3krit/walking-tag-action@master
        with:
          TAG_NAME: release
          TAG_MESSAGE: Latest release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
